### ISSUE TITLE
Cd2Assistant 插件HomePage api错误

### ISSUE THREAD

**Issue by androiddisk** [thsrite/MoviePilot-Plugins#173]
api 3001端口我是转发出来了的 

```
- My Third Group2:
    - CloudDrive2:
        href: http://172.17.0.1:19798/
        ping: http://172.17.0.1:19798
        #server: unraid
        #container: CloudDrive
        showStats: true
        display: list
        widget:
            type: customapi
            url: http://127.0.0.1:3001/api/v1/plugin/Cd2Assistant/homepage?apikey=bZdm5p_STS92dNAC6oavxa
            method: GET
            mappings:
                # - field: uptime
                #   label: 运行时间
                - field: upload_count
                  label: 上传数量
                - field: upload_speed
                  label: 上传速度
                - field: download_count
                  label: 下载数量
                - field: download_speed
                  label: 下载速度
                  
                # - field: cloud_space
                #   label: 剩余空间
```

![image](https://github.com/user-attachments/assets/3c080970-57b7-4f43-80c6-7e02862589bd)

手动访问也是报错
![image](https://github.com/user-attachments/assets/5f37a3d1-d706-428c-a4b5-49d80b4fc628)

mp日志没有显示
![image](https://github.com/user-attachments/assets/3f89cfc2-f6a8-4062-ae55-b546025ac46f)

插件加载时正常的
![image](https://github.com/user-attachments/assets/f48c5eb2-1c45-4c94-bcaa-8abfaee82fff)

插件日志也是正常的
![image](https://github.com/user-attachments/assets/ff99fa3b-fa1a-4f0c-a1b1-7510f519edcc)
